name: Publish to PyPI.org
on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
    build_sdist:
        name: Build source distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build sdist
              run: pipx run build --sdist ${{github.workspace}}/python/
            - name: Move sdist to dist
              run: mkdir -p dist && mv ${{github.workspace}}/python/dist/*.tar.gz dist/

            - uses: actions/upload-artifact@v3
              with:
                path: dist/*.tar.gz
                
    pypi:
        if: github.event_name == 'release'
        needs: build_sdist
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v3
              with:
                name: artifact
                path: dist
            
            - uses: pypa/gh-action-pypi-publish@release/v1
              with:
                password: ${{ secrets.PYPI_API_TOKEN }}
            


